name: Gitleaks
description: Run Gitleaks on Push and PR events
branding:
  color: purple
  icon: eye
inputs:
  commit-before:
    description: 'SHA of the commit before the push.'
    required: true
  config-path:
    description: 'Path to config (relative to $GITHUB_WORKSPACE)'
    required: false
    default: '.github/.gitleaks.toml'
  commit-after:
    description: 'SHA of the commit after the push.'
    required: false
outputs:
  result: # id of output
    description: 'Gitleaks log output'
  exitcode: # id of output
    description: 'Success for failure value from scan'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - 1234567890
    # - ${{ inputs.commit-before }}
    - ${{ inputs.config-path }}
    
