name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "ls"
      - name: gitleaks-action with defaults
        # uses: zricethezav/gitleaks-action@master
        uses: stone-z/gitleaks-action@scan-only-pushed-commits
      - name: gitleaks-action with config
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.yml
          commit-before: ${{ github.event.before }}
